apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustgate.fullname" . }}-data-plane
  labels:
    {{- include "trustgate.dataPlane.labels" . | nindent 4 }}
    component: data-plane
spec:
  replicas: {{ .Values.dataPlane.replicas }}
  selector:
    matchLabels:
      {{- include "trustgate.dataPlane.labels" . | nindent 6 }}
      component: data-plane
  template:
    metadata:
      labels:
        {{- include "trustgate.dataPlane.labels" . | nindent 8 }}
        component: data-plane
    spec:
      containers:
      - name: data-plane
        image: "{{ .Values.dataPlane.image.repository }}:{{ .Values.dataPlane.image.tag }}"
        args: ["proxy"]
        env:
        # Core configuration
        - name: LOG_LEVEL
          value: {{ .Values.dataPlane.env.LOG_LEVEL | default "info" }}
        - name: SERVER_BASE_DOMAIN
          value: {{ .Values.dataPlane.env.SERVER_BASE_DOMAIN | default "example.com" }}
        - name: SERVER_ADMIN_PORT
          value: {{ .Values.dataPlane.env.SERVER_ADMIN_PORT | default "8080" | quote }}
        - name: SERVER_METRICS_PORT
          value: {{ .Values.dataPlane.env.SERVER_METRICS_PORT | default "9090" | quote }}
        - name: SERVER_PROXY_PORT
          value: {{ .Values.dataPlane.env.SERVER_PROXY_PORT | default "8081" | quote }}
        
        # Database configuration
        - name: DATABASE_HOST
          value: {{ include "trustgate.postgresql.host" . }}
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "trustgate.postgresql.secretName" . }}
              key: password
        - name: DATABASE_NAME
          value: {{ .Values.postgresql.auth.database }}
        - name: DATABASE_SSL_MODE
          value: {{ .Values.dataPlane.env.DATABASE_SSL_MODE | default "disable" }}
        
        # Redis configuration
        - name: REDIS_HOST
          value: {{ include "trustgate.redis.host" . }}-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "trustgate.redis.secretName" . }}
              key: redis-password
        - name: REDIS_DB
          value: "0"
        
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dataPlane.ports.http }}
          name: http
        resources:
          {{- toYaml .Values.dataPlane.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dataPlane.podSecurityContext | nindent 8 }}
      {{- with .Values.dataPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 