apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustgate.fullname" . }}-data-plane
  labels:
    {{- include "trustgate.dataPlane.labels" . | nindent 4 }}
    component: data-plane
spec:
  replicas: {{ .Values.dataPlane.replicas }}
  selector:
    matchLabels:
      {{- include "trustgate.dataPlane.labels" . | nindent 6 }}
      component: data-plane
  template:
    metadata:
      labels:
        {{- include "trustgate.dataPlane.labels" . | nindent 8 }}
        component: data-plane
    spec:
      containers:
      - name: data-plane
        image: "{{ .Values.dataPlane.image.repository }}:{{ .Values.dataPlane.image.tag }}"
        args: ["proxy"]
        env:
        - name: CONFIG_PATH
          value: "/etc/trustgate/config.yaml"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "trustgate.fullname" . }}-secrets
              key: postgresql-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "trustgate.fullname" . }}-secrets
              key: redis-password
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dataPlane.ports.http }}
          name: http
        resources:
          {{- toYaml .Values.dataPlane.resources | nindent 10 }}
        volumeMounts:
          - name: config
            mountPath: /etc/trustgate/config.yaml
            subPath: config.yaml
          - name: secrets
            mountPath: /etc/trustgate/secrets
            readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dataPlane.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "trustgate.fullname" . }}-config
        - name: secrets
          secret:
            secretName: {{ include "trustgate.fullname" . }}-secrets
      {{- with .Values.dataPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 