{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustgate.fullname" . }}-nginx-configuration
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: nginx-controller
data:
  allow-snippet-annotations: "false"
{{- end }}