apiVersion: v1
kind: Service
metadata:
  name: {{ include "trustgate.fullname" . }}-nginx-controller
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: nginx-controller
  annotations:
    {{- with .Values.ingressController.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.ingressController.service.type | default "LoadBalancer" }}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    {{- include "trustgate.selectorLabels" . | nindent 4 }}
    component: nginx-controller 