apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustgate.fullname" . }}-firewall
  labels:
    {{- include "trustgate.firewall.labels" . | nindent 4 }}
    component: firewall
spec:
  replicas: {{ .Values.firewall.replicas }}
  selector:
    matchLabels:
      {{- include "trustgate.firewall.labels" . | nindent 6 }}
      component: firewall
  template:
    metadata:
      labels:
        {{- include "trustgate.firewall.labels" . | nindent 8 }}
        component: firewall
    spec:
      containers:
      - name: firewall
        image: "{{ .Values.firewall.image.repository }}:{{ .Values.firewall.image.tag }}"
        args: ["proxy"]
        env:
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-api-key
              key: HUGGINGFACE_TOKEN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: firewall-jwt-secret
              key: JWT_SECRET
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.firewall.ports.http }}
          name: http
        resources:
          {{- toYaml .Values.firewall.resources | nindent 10 }}
        volumeMounts:
          - name: huggingface-cache
            mountPath: "/root/.cache/huggingface"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-huggingface-cache"
      {{- with .Values.firewall.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.firewall.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.firewall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 