{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trustgate.fullname" . }}-postgresql
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: postgresql
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "trustgate.selectorLabels" . | nindent 4 }}
    component: postgresql
{{- end }}
---