{{- if and .Values.monitoring.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trustgate.fullname" . }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "trustgate.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_component]
          targetLabel: component
          regex: control-plane
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }} 