apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-actions
  labels:
    {{- include "trustgate.actions.labels" . | nindent 4 }}
    component: actions
spec:
  replicas: {{ .Values.actions.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "trustgate.actions.labels" . | nindent 6 }}
      component: actions
  template:
    metadata:
      labels:
        {{- include "trustgate.actions.labels" . | nindent 8 }}
        component: actions
    spec:
      {{- if ne .Values.global.version "ce" }}
      imagePullSecrets:
        {{- toYaml .Values.global.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
      - name: logs-volume
        emptyDir: {}
      containers:
      - name: actions
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        args: ["admin"]
        envFrom:
        - secretRef:
            name: {{ include "trustgate.fullname" . }}-env-vars
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        ports:
        - containerPort: {{ .Values.actions.ports.http }}
          name: http
        resources:
          {{- toYaml .Values.actions.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-actions
  labels:
    {{- include "trustgate.actions.labels" . | nindent 4 }}
    component: actions
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.actions.ports.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "trustgate.actions.labels" . | nindent 4 }}
    component: actions 