{{- if .Values.moderation.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustgate.fullname" . }}-moderation
  labels:
    {{- include "trustgate.moderation.labels" . | nindent 4 }}
    component: moderation
spec:
  replicas: {{ .Values.moderation.replicas }}
  selector:
    matchLabels:
      {{- include "trustgate.moderation.labels" . | nindent 6 }}
      component: moderation
  template:
    metadata:
      labels:
        {{- include "trustgate.moderation.labels" . | nindent 8 }}
        component: moderation
    spec:
      imagePullSecrets:
        {{- toYaml .Values.global.image.imagePullSecrets | nindent 8 }}
      containers:
      - name: moderation
        image: "{{ .Values.moderation.image.repository }}:{{ .Values.moderation.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-api-key
              key: HUGGINGFACE_TOKEN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: firewall-jwt-secret
              key: JWT_SECRET
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.moderation.ports.http }}
          name: http
        resources:
          {{- toYaml .Values.moderation.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-moderation
  labels:
    {{- include "trustgate.moderation.labels" . | nindent 4 }}
    component: moderation
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.moderation.ports.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "trustgate.moderation.labels" . | nindent 4 }}
    component: moderation 
{{- end }}