apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-control-plane
  labels:
    {{- include "trustgate.controlPlane.labels" . | nindent 4 }}
    component: control-plane
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.controlPlane.ports.proxy }}
      protocol: TCP
      name: http
  selector:
    {{- include "trustgate.controlPlane.labels" . | nindent 4 }}
    component: control-plane 