# Control Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trustgate.fullname" . }}-admin
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: control-plane
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.certManager.enabled}}
  tls:
    - hosts:
        - admin.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      secretName: trustgate-admin-tls
  {{- end }}
  rules:
    - host: admin.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trustgate.fullname" . }}-control-plane
                port:
                  number: {{ .Values.controlPlane.ports.http }}
---
# Data Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trustgate.fullname" . }}-gateway
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: data-plane
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.certManager.enabled}}
  tls:
    - hosts:
        - gateway.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      secretName: trustgate-gateway-tls
  {{- end }}
  rules:
    - host: gateway.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trustgate.fullname" . }}-data-plane
                port:
                  number: {{ .Values.dataPlane.ports.http }}