{{- if .Values.ingress.enabled }}
# Control Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trustgate.fullname" . }}-admin
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: control-plane
  {{- with .Values.ingress.annotations }}
  annotations:
    cert-manager.io/cluster-issuer: "trustgate-letsencrypt-prod"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or .Values.certManager.enabled .Values.certManager.customCertificates.enabled }}
  tls:
    - hosts:
        - admin.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      secretName: trustgate-admin-tls
  {{- end }}
  rules:
    - host: admin.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trustgate.fullname" . }}-control-plane
                port:
                  number: {{ .Values.controlPlane.ports.proxy }}
---
# Data Plane Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trustgate.fullname" . }}-gateway
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
    component: data-plane
  annotations:
    cert-manager.io/cluster-issuer: "trustgate-letsencrypt-prod"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or .Values.certManager.enabled .Values.certManager.customCertificates.enabled }}
  tls:
    - hosts:
        - gateway.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      secretName: trustgate-gateway-tls
  {{- end }}
  rules:
    - host: gateway.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trustgate.fullname" . }}-data-plane
                port:
                  number: {{ .Values.dataPlane.ports.http }}
{{- if and .Values.firewall.enabled .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trustgate.fullname" . }}-firewall
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if or .Values.certManager.enabled .Values.certManager.customCertificates.enabled }}
  tls:
    - hosts:
        - firewall.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      secretName: trustgate-firewall-tls
  {{- end }}
  rules:
    - host: firewall.{{ .Values.global.env.SERVER_BASE_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trustgate.fullname" . }}-firewall
                port:
                  number: {{ .Values.firewall.ports.http }}
{{- end }}
{{- end }} 