apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trustgate.serviceAccountName" . }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "trustgate.fullname" . }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "trustgate.fullname" . }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "trustgate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trustgate.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }} 