apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trustgate.fullname" . }}-secrets
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $provider, $config := .Values.config.providers }}
  {{- if $config.apiKey }}
  {{ $provider }}-api-key: {{ $config.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  postgresql-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc | quote }}

{{- if .Values.certManager.customCertificates.enabled }}
---
# Control Plane custom certificate
apiVersion: v1
kind: Secret
metadata:
  name: trustgate-admin-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certManager.customCertificates.controlPlane.cert | b64enc }}
  tls.key: {{ .Values.certManager.customCertificates.controlPlane.key | b64enc }}
---
# Data Plane custom certificate
apiVersion: v1
kind: Secret
metadata:
  name: trustgate-gateway-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certManager.customCertificates.dataPlane.cert | b64enc }}
  tls.key: {{ .Values.certManager.customCertificates.dataPlane.key | b64enc }}
{{- end }}