apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trustgate.fullname" . }}-secrets
  labels:
    {{- include "trustgate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $provider, $config := .Values.config.providers }}
  {{- if $config.apiKey }}
  {{ $provider }}-api-key: {{ $config.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  postgresql-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc | quote }}